#include <algorithm>
#include <chrono>
#include <cmath>
#include <memory>

#include "control_node.hpp"


ControlNode::ControlNode()
: Node("control"),
  control_(robot::ControlCore(this->get_logger())),
  have_path_(false),
  have_odom_(false),
  lookahead_distance_(1.0),
  goal_tolerance_(0.35),
  linear_speed_(0.5),
  max_angular_speed_(1.5)
{
  // Subscribe to the path generated by the planner
  path_sub_ =
    this->create_subscription<nav_msgs::msg::Path>(
      "/path",
      10,
      std::bind(
        &ControlNode::pathCallback,
        this,
        std::placeholders::_1
      )
    );


  // Subscribe to the robot's current odometry
  odom_sub_ =
    this->create_subscription<nav_msgs::msg::Odometry>(
      "/odom/filtered",
      10,
      std::bind(
        &ControlNode::odomCallback,
        this,
        std::placeholders::_1
      )
    );


  // Publish velocity commands to the robot
  cmd_vel_pub_ =
    this->create_publisher<geometry_msgs::msg::Twist>(
      "/cmd_vel",
      10
    );


  // Run the controller at 10 Hz
  control_timer_ =
    this->create_wall_timer(
      std::chrono::milliseconds(100),
      std::bind(
        &ControlNode::controlLoop,
        this
      )
    );
}


// Stores the newest path
void ControlNode::pathCallback(
  const nav_msgs::msg::Path::SharedPtr msg)
{
  current_path_ = *msg;

  have_path_ = true;


  // An empty path means there is nothing to follow
  if (current_path_.poses.empty()) {

    publishStop();
  }
}


// Stores the newest robot pose
void ControlNode::odomCallback(
  const nav_msgs::msg::Odometry::SharedPtr msg)
{
  robot_odom_ = *msg;

  have_odom_ = true;
}


// Calculates the distance between two points
double ControlNode::computeDistance(
  const geometry_msgs::msg::Point & a,
  const geometry_msgs::msg::Point & b) const
{
  double dx = b.x - a.x;

  double dy = b.y - a.y;


  return std::sqrt(
    dx * dx +
    dy * dy
  );
}


// Converts quaternion orientation into yaw
double ControlNode::extractYaw(
  const geometry_msgs::msg::Quaternion & quat) const
{
  double siny_cosp =
    2.0 *
    (quat.w * quat.z +
     quat.x * quat.y);


  double cosy_cosp =
    1.0 -
    2.0 *
    (quat.y * quat.y +
     quat.z * quat.z);


  return std::atan2(
    siny_cosp,
    cosy_cosp
  );
}


// Finds a point ahead of the robot along the path
bool ControlNode::findLookaheadPoint(
  geometry_msgs::msg::PoseStamped & target) const
{
  if (!have_path_ ||
      !have_odom_ ||
      current_path_.poses.empty()) {

    return false;
  }


  const geometry_msgs::msg::Point &
    robot_position =
      robot_odom_.pose.pose.position;


  // First find the path point closest to the robot
  std::size_t closest_index = 0;

  double closest_distance =
    computeDistance(
      robot_position,
      current_path_.poses[0].pose.position
    );


  for (std::size_t i = 1;
       i < current_path_.poses.size();
       ++i) {

    double distance =
      computeDistance(
        robot_position,
        current_path_.poses[i].pose.position
      );


    if (distance < closest_distance) {

      closest_distance = distance;

      closest_index = i;
    }
  }


  // Starting from the closest point,
  // find the first point at least one
  // lookahead distance away
  for (std::size_t i = closest_index;
       i < current_path_.poses.size();
       ++i) {

    double distance =
      computeDistance(
        robot_position,
        current_path_.poses[i].pose.position
      );


    if (distance >= lookahead_distance_) {

      target = current_path_.poses[i];

      return true;
    }
  }


  // If no point is far enough away,
  // use the final path point
  target = current_path_.poses.back();

  return true;
}


// Publishes zero velocity to stop the robot
void ControlNode::publishStop()
{
  geometry_msgs::msg::Twist stop_command;

  stop_command.linear.x = 0.0;

  stop_command.angular.z = 0.0;

  cmd_vel_pub_->publish(stop_command);
}


// Main Pure Pursuit controller
void ControlNode::controlLoop()
{
  if (!have_odom_) {

    return;
  }


  if (!have_path_ ||
      current_path_.poses.empty()) {

    publishStop();

    return;
  }


  const geometry_msgs::msg::Point &
    robot_position =
      robot_odom_.pose.pose.position;


  const geometry_msgs::msg::Point &
    goal_position =
      current_path_.poses.back().pose.position;


  // Stop once the robot is close enough to the goal
  double distance_to_goal =
    computeDistance(
      robot_position,
      goal_position
    );


  if (distance_to_goal <= goal_tolerance_) {

    publishStop();

    return;
  }


  // Find a point ahead on the path
  geometry_msgs::msg::PoseStamped target;


  if (!findLookaheadPoint(target)) {

    publishStop();

    return;
  }


  double robot_yaw =
    extractYaw(
      robot_odom_.pose.pose.orientation
    );


  double dx =
    target.pose.position.x -
    robot_position.x;


  double dy =
    target.pose.position.y -
    robot_position.y;


  // Desired direction toward the lookahead point
  double desired_heading =
    std::atan2(
      dy,
      dx
    );


  // Difference between where the robot is facing
  // and where it needs to face
  double heading_error =
    desired_heading -
    robot_yaw;


  // Normalize the heading error to -pi to pi
  heading_error =
    std::atan2(
      std::sin(heading_error),
      std::cos(heading_error)
    );


  geometry_msgs::msg::Twist command;


  /*
   * If the target point is far to the side or behind
   * the robot, turn first instead of driving forward.
   */
  if (std::fabs(heading_error) > 1.0) {

    command.linear.x = 0.0;

    command.angular.z =
      std::clamp(
        heading_error,
        -max_angular_speed_,
        max_angular_speed_
      );
  }


  else {

    /*
     * Convert the target point into the robot's
     * local coordinate frame.
     *
     * Pure Pursuit curvature:
     *
     * curvature = 2 * local_y / L^2
     */

    double local_y =
      (-std::sin(robot_yaw) * dx) +
      ( std::cos(robot_yaw) * dy);


    double lookahead_squared =
      dx * dx +
      dy * dy;


    if (lookahead_squared < 0.000001) {

      publishStop();

      return;
    }


    double curvature =
      (2.0 * local_y) /
      lookahead_squared;


    command.linear.x =
      linear_speed_;


    command.angular.z =
      linear_speed_ *
      curvature;


    // Prevent extremely large angular velocities
    command.angular.z =
      std::clamp(
        command.angular.z,
        -max_angular_speed_,
        max_angular_speed_
      );
  }


  // Send the velocity command to the robot
  cmd_vel_pub_->publish(command);
}


int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);

  rclcpp::spin(
    std::make_shared<ControlNode>()
  );

  rclcpp::shutdown();

  return 0;
}