#ifndef CONTROL_NODE_HPP_
#define CONTROL_NODE_HPP_

#include "rclcpp/rclcpp.hpp"

#include "nav_msgs/msg/path.hpp"
#include "nav_msgs/msg/odometry.hpp"

#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/pose_stamped.hpp"
#include "geometry_msgs/msg/point.hpp"
#include "geometry_msgs/msg/quaternion.hpp"

#include "control_core.hpp"

class ControlNode : public rclcpp::Node {

  public:

    ControlNode();

  private:

    robot::ControlCore control_;

    // Receives the path generated by the planner
    rclcpp::Subscription<nav_msgs::msg::Path>::SharedPtr path_sub_;

    // Receives the robot's current position and orientation
    rclcpp::Subscription<nav_msgs::msg::Odometry>::SharedPtr odom_sub_;

    // Publishes linear and angular velocity commands
    rclcpp::Publisher<geometry_msgs::msg::Twist>::SharedPtr cmd_vel_pub_;

    // Runs the Pure Pursuit controller repeatedly
    rclcpp::TimerBase::SharedPtr control_timer_;

    // Stores the most recently received path
    nav_msgs::msg::Path current_path_;

    // Stores the most recently received odometry
    nav_msgs::msg::Odometry robot_odom_;

    bool have_path_;
    bool have_odom_;

    // Pure Pursuit parameters
    double lookahead_distance_;
    double goal_tolerance_;
    double linear_speed_;
    double max_angular_speed_;

    // Callback functions
    void pathCallback(
      const nav_msgs::msg::Path::SharedPtr msg);

    void odomCallback(
      const nav_msgs::msg::Odometry::SharedPtr msg);

    // Main Pure Pursuit control loop
    void controlLoop();

    // Finds a point ahead of the robot on the path
    bool findLookaheadPoint(
      geometry_msgs::msg::PoseStamped & target) const;

    // Calculates the distance between two points
    double computeDistance(
      const geometry_msgs::msg::Point & a,
      const geometry_msgs::msg::Point & b) const;

    // Converts quaternion orientation into yaw
    double extractYaw(
      const geometry_msgs::msg::Quaternion & quat) const;

    // Stops the robot
    void publishStop();
};

#endif