#include <algorithm>
#include <chrono>
#include <cmath>
#include <limits>
#include <memory>
#include <queue>
#include <vector>

#include "planner_node.hpp"


PlannerNode::PlannerNode()
: Node("planner"),
  planner_(robot::PlannerCore(this->get_logger())),
  state_(State::WAITING_FOR_GOAL),
  have_map_(false),
  have_odom_(false),
  goal_received_(false)
{
  // Receives the global occupancy grid
  map_sub_ =
    this->create_subscription<nav_msgs::msg::OccupancyGrid>(
      "/map",
      10,
      std::bind(
        &PlannerNode::mapCallback,
        this,
        std::placeholders::_1
      )
    );


  // Receives the goal selected by the user
  goal_sub_ =
    this->create_subscription<geometry_msgs::msg::PointStamped>(
      "/goal_point",
      10,
      std::bind(
        &PlannerNode::goalCallback,
        this,
        std::placeholders::_1
      )
    );


  // Receives the robot's current position
  odom_sub_ =
    this->create_subscription<nav_msgs::msg::Odometry>(
      "/odom/filtered",
      10,
      std::bind(
        &PlannerNode::odomCallback,
        this,
        std::placeholders::_1
      )
    );


  // Publishes the path generated by A*
  path_pub_ =
    this->create_publisher<nav_msgs::msg::Path>(
      "/path",
      10
    );


  // Checks the planner state once every second
  timer_ =
    this->create_wall_timer(
      std::chrono::seconds(1),
      std::bind(
        &PlannerNode::timerCallback,
        this
      )
    );
}


// Stores the newest global map
void PlannerNode::mapCallback(
  const nav_msgs::msg::OccupancyGrid::SharedPtr msg)
{
  current_map_ = *msg;

  have_map_ = true;


  // If the robot is currently trying to reach a goal,
  // replan whenever the map changes
  if (state_ ==
        State::WAITING_FOR_ROBOT_TO_REACH_GOAL &&
      have_odom_ &&
      goal_received_) {

    planPath();
  }
}


// Stores a newly selected goal
void PlannerNode::goalCallback(
  const geometry_msgs::msg::PointStamped::SharedPtr msg)
{
  goal_ = *msg;

  goal_received_ = true;

  state_ =
    State::WAITING_FOR_ROBOT_TO_REACH_GOAL;


  RCLCPP_INFO(
    this->get_logger(),
    "Received goal: (%.2f, %.2f)",
    goal_.point.x,
    goal_.point.y
  );


  if (have_map_ && have_odom_) {

    planPath();
  }
}


// Stores the robot's current pose
void PlannerNode::odomCallback(
  const nav_msgs::msg::Odometry::SharedPtr msg)
{
  robot_pose_ = msg->pose.pose;

  have_odom_ = true;
}


// Periodically checks whether the goal has been reached
// and replans if the robot is still moving toward the goal
void PlannerNode::timerCallback()
{
  if (state_ !=
      State::WAITING_FOR_ROBOT_TO_REACH_GOAL) {

    return;
  }


  if (!have_map_ ||
      !have_odom_ ||
      !goal_received_) {

    return;
  }


  if (goalReached()) {

    RCLCPP_INFO(
      this->get_logger(),
      "Goal reached!"
    );


    state_ =
      State::WAITING_FOR_GOAL;

    goal_received_ = false;


    // Publish an empty path when the goal is reached
    nav_msgs::msg::Path empty_path;

    empty_path.header.stamp =
      this->get_clock()->now();

    empty_path.header.frame_id =
      current_map_.header.frame_id;

    path_pub_->publish(empty_path);

    return;
  }


  // Replan periodically while the robot moves
  planPath();
}


// Checks whether the robot is close enough to the goal
bool PlannerNode::goalReached() const
{
  double dx =
    goal_.point.x -
    robot_pose_.position.x;

  double dy =
    goal_.point.y -
    robot_pose_.position.y;


  double distance =
    std::sqrt(
      dx * dx +
      dy * dy
    );


  return distance < 0.5;
}


// Converts world coordinates into occupancy-grid coordinates
bool PlannerNode::worldToGrid(
  double world_x,
  double world_y,
  int & grid_x,
  int & grid_y) const
{
  if (current_map_.info.resolution <= 0.0) {

    return false;
  }


  grid_x =
    static_cast<int>(
      std::floor(
        (world_x -
         current_map_.info.origin.position.x) /
        current_map_.info.resolution
      )
    );


  grid_y =
    static_cast<int>(
      std::floor(
        (world_y -
         current_map_.info.origin.position.y) /
        current_map_.info.resolution
      )
    );


  if (grid_x < 0 ||
      grid_y < 0 ||
      grid_x >=
        static_cast<int>(
          current_map_.info.width
        ) ||
      grid_y >=
        static_cast<int>(
          current_map_.info.height
        )) {

    return false;
  }


  return true;
}


// Converts occupancy-grid coordinates back into world coordinates
void PlannerNode::gridToWorld(
  int grid_x,
  int grid_y,
  double & world_x,
  double & world_y) const
{
  world_x =
    current_map_.info.origin.position.x +
    (static_cast<double>(grid_x) + 0.5) *
    current_map_.info.resolution;


  world_y =
    current_map_.info.origin.position.y +
    (static_cast<double>(grid_y) + 0.5) *
    current_map_.info.resolution;
}


// Determines whether A* can enter a cell
bool PlannerNode::isTraversable(
  int grid_x,
  int grid_y) const
{
  if (grid_x < 0 ||
      grid_y < 0 ||
      grid_x >=
        static_cast<int>(
          current_map_.info.width
        ) ||
      grid_y >=
        static_cast<int>(
          current_map_.info.height
        )) {

    return false;
  }


  int index =
    grid_y *
    current_map_.info.width +
    grid_x;


  int cell_value =
    current_map_.data[index];


  // Unknown cells are allowed.
  // As the map learns about new obstacles,
  // the planner will replan.
  if (cell_value < 0) {

    return true;
  }


  // Cells with a high obstacle cost are blocked
  return cell_value < 50;
}


// Euclidean distance heuristic used by A*
double PlannerNode::heuristic(
  int x1,
  int y1,
  int x2,
  int y2) const
{
  double dx =
    static_cast<double>(x2 - x1);

  double dy =
    static_cast<double>(y2 - y1);


  return std::sqrt(
    dx * dx +
    dy * dy
  );
}


// Finds a path from the robot to the goal using A*
void PlannerNode::planPath()
{
  if (!have_map_ ||
      !have_odom_ ||
      !goal_received_ ||
      current_map_.data.empty()) {

    return;
  }


  int start_x;
  int start_y;

  int goal_x;
  int goal_y;


  // Convert the robot's world position into a grid cell
  if (!worldToGrid(
        robot_pose_.position.x,
        robot_pose_.position.y,
        start_x,
        start_y)) {

    RCLCPP_WARN(
      this->get_logger(),
      "Robot position is outside the map."
    );

    return;
  }


  // Convert the requested goal into a grid cell
  if (!worldToGrid(
        goal_.point.x,
        goal_.point.y,
        goal_x,
        goal_y)) {

    RCLCPP_WARN(
      this->get_logger(),
      "Goal position is outside the map."
    );

    return;
  }


  if (!isTraversable(start_x, start_y)) {

    RCLCPP_WARN(
      this->get_logger(),
      "Robot starting cell is occupied."
    );

    return;
  }


  if (!isTraversable(goal_x, goal_y)) {

    RCLCPP_WARN(
      this->get_logger(),
      "Goal cell is occupied."
    );

    return;
  }


  const int width =
    static_cast<int>(
      current_map_.info.width
    );

  const int height =
    static_cast<int>(
      current_map_.info.height
    );

  const int total_cells =
    width * height;


  const int start_index =
    start_y * width + start_x;

  const int goal_index =
    goal_y * width + goal_x;


  // Stores the best known cost from the start
  // to every map cell
  std::vector<double> g_score(
    total_cells,
    std::numeric_limits<double>::infinity()
  );


  // Stores the previous cell so that the final
  // path can be reconstructed backwards
  std::vector<int> came_from(
    total_cells,
    -1
  );


  // Prevents already-completed cells from
  // being processed repeatedly
  std::vector<bool> closed(
    total_cells,
    false
  );


  std::priority_queue<
    GridNode,
    std::vector<GridNode>,
    CompareNode
  > open_set;


  g_score[start_index] = 0.0;


  open_set.push(
    GridNode(
      start_index,
      heuristic(
        start_x,
        start_y,
        goal_x,
        goal_y
      )
    )
  );


  // Allows movement in all eight directions
  const int direction_x[8] =
    {1, -1, 0, 0, 1, 1, -1, -1};

  const int direction_y[8] =
    {0, 0, 1, -1, 1, -1, 1, -1};


  bool path_found = false;


  while (!open_set.empty()) {

    GridNode current =
      open_set.top();

    open_set.pop();


    int current_index =
      current.index;


    if (closed[current_index]) {

      continue;
    }


    closed[current_index] = true;


    // Stop once A* reaches the goal
    if (current_index == goal_index) {

      path_found = true;

      break;
    }


    int current_x =
      current_index % width;

    int current_y =
      current_index / width;


    // Check every neighboring cell
    for (int direction = 0;
         direction < 8;
         ++direction) {

      int next_x =
        current_x +
        direction_x[direction];

      int next_y =
        current_y +
        direction_y[direction];


      if (!isTraversable(
            next_x,
            next_y)) {

        continue;
      }


      bool diagonal =
        direction_x[direction] != 0 &&
        direction_y[direction] != 0;


      // Prevent diagonal movement through
      // the corner of an obstacle
      if (diagonal) {

        if (!isTraversable(
              current_x +
              direction_x[direction],
              current_y) ||
            !isTraversable(
              current_x,
              current_y +
              direction_y[direction])) {

          continue;
        }
      }


      int next_index =
        next_y * width +
        next_x;


      if (closed[next_index]) {

        continue;
      }


      double movement_cost =
        diagonal ?
        std::sqrt(2.0) :
        1.0;


      int occupancy_cost =
        current_map_.data[next_index];


      // Add a small penalty for cells close to obstacles
      if (occupancy_cost > 0) {

        movement_cost +=
          static_cast<double>(
            occupancy_cost
          ) / 100.0;
      }


      double tentative_g =
        g_score[current_index] +
        movement_cost;


      if (tentative_g <
          g_score[next_index]) {

        came_from[next_index] =
          current_index;


        g_score[next_index] =
          tentative_g;


        double f_score =
          tentative_g +
          heuristic(
            next_x,
            next_y,
            goal_x,
            goal_y
          );


        open_set.push(
          GridNode(
            next_index,
            f_score
          )
        );
      }
    }
  }


  nav_msgs::msg::Path path;

  path.header.stamp =
    this->get_clock()->now();


  if (current_map_.header.frame_id.empty()) {

    path.header.frame_id =
      "sim_world";
  }

  else {

    path.header.frame_id =
      current_map_.header.frame_id;
  }


  // If A* cannot reach the goal,
  // publish an empty path
  if (!path_found) {

    RCLCPP_WARN(
      this->get_logger(),
      "No path to the goal was found."
    );

    path_pub_->publish(path);

    return;
  }


  // Reconstruct the path by moving backwards
  // from the goal to the starting cell
  std::vector<int> path_indices;


  int current_index =
    goal_index;


  while (current_index != -1) {

    path_indices.push_back(
      current_index
    );


    if (current_index ==
        start_index) {

      break;
    }


    current_index =
      came_from[current_index];
  }


  // Reverse it so it runs from robot to goal
  std::reverse(
    path_indices.begin(),
    path_indices.end()
  );


  // Convert every grid cell into a PoseStamped
  for (int index : path_indices) {

    int grid_x =
      index % width;

    int grid_y =
      index / width;


    double world_x;
    double world_y;


    gridToWorld(
      grid_x,
      grid_y,
      world_x,
      world_y
    );


    geometry_msgs::msg::PoseStamped pose;


    pose.header =
      path.header;


    pose.pose.position.x =
      world_x;

    pose.pose.position.y =
      world_y;

    pose.pose.position.z =
      0.0;


    pose.pose.orientation.x =
      0.0;

    pose.pose.orientation.y =
      0.0;

    pose.pose.orientation.z =
      0.0;

    pose.pose.orientation.w =
      1.0;


    path.poses.push_back(
      pose
    );
  }


  RCLCPP_INFO(
    this->get_logger(),
    "Publishing path with %zu points.",
    path.poses.size()
  );


  path_pub_->publish(path);
}


int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);

  rclcpp::spin(
    std::make_shared<PlannerNode>()
  );

  rclcpp::shutdown();

  return 0;
}